"""Command-line application and setup wizard for Next Level."""

from __future__ import annotations

import argparse
import getpass
import os
import plistlib
import shlex
import subprocess
import sys
from collections.abc import Callable, Sequence
from pathlib import Path

import pytz
import telebot

import bot

APP_NAME = "NextLevelBot"


def _prompt(label: str, default: str = "", *, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    reader: Callable[[str], str] = getpass.getpass if secret else input
    value = reader(f"{label}{suffix}: ").strip()
    return value or default


def _yes_no(label: str, *, default: bool = True) -> bool:
    marker = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{marker}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes", "д", "да"}:
            return True
        if value in {"n", "no", "н", "нет"}:
            return False
        print("Enter yes or no / Введите да или нет.")


def _dotenv_value(value: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError("Configuration values cannot contain line breaks")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _data_dir() -> Path:
    if os.name == "nt":
        root = os.getenv("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
        return Path(root) / "NextLevel" / "data"
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "NextLevel" / "data"
    root = os.getenv("XDG_STATE_HOME", "").strip()
    return (Path(root).expanduser() if root else Path.home() / ".local" / "state") / "nextlevel"


def verify_telegram(token: str, channel_id: str) -> tuple[bool, str]:
    """Verify bot credentials and administrator access without posting."""
    try:
        client = telebot.TeleBot(token)
        identity = client.get_me()
        chat = client.get_chat(channel_id)
        membership = client.get_chat_member(channel_id, identity.id)
    except Exception as exc:  # noqa: BLE001 - client errors vary by transport/API.
        safe_error = str(exc).replace(token, "<redacted>") if token else str(exc)
        return False, f"Telegram verification failed: {safe_error}"

    status = getattr(membership, "status", "unknown")
    if status not in {"administrator", "creator"}:
        return (
            False,
            (
                f"@{identity.username} can see {chat.title!r}, but is not an "
                f"administrator (status: {status})."
            ),
        )
    return True, f"Connected @{identity.username} to {chat.title!r} ({channel_id})."


def write_config(
    path: Path,
    *,
    token: str,
    channel_id: str,
    timezone_name: str,
    post_times: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        (
            "# Generated by `nextlevel setup`. Do not commit this file.",
            f"TELEGRAM_BOT_TOKEN={_dotenv_value(token)}",
            f"TELEGRAM_CHANNEL_ID={_dotenv_value(channel_id)}",
            f"TIMEZONE={_dotenv_value(timezone_name)}",
            f"POST_TIMES={_dotenv_value(post_times)}",
            "MAX_POSTS_PER_RUN=5",
            "HOURS_LOOKBACK=48",
            f"DATA_DIR={_dotenv_value(str(_data_dir()))}",
            "REQUEST_TIMEOUT=15",
            "POST_DELAY_SECONDS=2",
            "LOG_LEVEL=INFO",
            "LLM_API_KEY=",
            "LLM_BASE_URL=https://api.openai.com/v1",
            "LLM_MODEL=",
            "",
        )
    )
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    if os.name != "nt":
        temporary.chmod(0o600)
    temporary.replace(path)


def setup() -> int:
    print("\nNext Level setup / Настройка Next Level\n")
    print("Create a bot with @BotFather and add it as a channel administrator first.")
    print("Сначала создайте бота через @BotFather и добавьте его администратором канала.\n")

    token = _prompt("Telegram Bot Token / токен", secret=True)
    channel_id = _prompt("Channel ID / ID канала (for example @nextlvlgm)")
    timezone_name = _prompt("Timezone / часовой пояс", "Europe/Warsaw")
    while timezone_name not in pytz.all_timezones_set:
        print("Unknown IANA timezone. Example: Europe/Warsaw or Asia/Kamchatka.")
        timezone_name = _prompt("Timezone / часовой пояс", "Europe/Warsaw")

    post_times = _prompt("Post times / время публикаций", "10:00,19:00")
    try:
        normalized_times = ",".join(bot.parse_post_times(post_times))
    except bot.ConfigurationError as exc:
        print(f"Invalid schedule / неверное расписание: {exc}", file=sys.stderr)
        return 2

    ok, message = verify_telegram(token, channel_id)
    print(message)
    if not ok:
        print("Configuration was not saved. Fix Telegram access and run setup again.")
        return 2

    path = bot.default_env_file()
    write_config(
        path,
        token=token,
        channel_id=channel_id,
        timezone_name=timezone_name,
        post_times=normalized_times,
    )
    print(f"Configuration saved: {path}")

    if _yes_no("Enable automatic startup / включить автозапуск?", default=True):
        if install_autostart():
            print("Automatic startup enabled / Автозапуск включён.")
        else:
            print("Could not enable autostart; you can still run `nextlevel run`.")
    print("\nReady. Preview: nextlevel preview")
    return 0


def _module_command() -> list[str]:
    return [sys.executable, "-m", "bot"]


def _linux_service_path() -> Path:
    return Path.home() / ".config" / "systemd" / "user" / "nextlevel.service"


def _systemd_environment(name: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'Environment="{name}={escaped}"'


def install_autostart() -> bool:
    command = _module_command()
    env_file = bot.default_env_file().resolve()
    if os.name == "nt":
        action = subprocess.list2cmdline(command)
        result = subprocess.run(
            [
                "schtasks",
                "/Create",
                "/TN",
                APP_NAME,
                "/TR",
                action,
                "/SC",
                "ONLOGON",
                "/F",
            ],
            check=False,
        )
        if result.returncode != 0:
            return False
        started = subprocess.run(
            ["schtasks", "/Run", "/TN", APP_NAME], check=False
        )
        return started.returncode == 0

    if sys.platform == "darwin":
        path = Path.home() / "Library" / "LaunchAgents" / "io.github.nextlevel.bot.plist"
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "Label": "io.github.nextlevel.bot",
            "ProgramArguments": command,
            "EnvironmentVariables": {"NEXTLEVEL_ENV_FILE": str(env_file)},
            "RunAtLoad": True,
            "KeepAlive": True,
        }
        path.write_bytes(plistlib.dumps(payload))
        result = subprocess.run(["launchctl", "load", "-w", str(path)], check=False)
        return result.returncode == 0

    path = _linux_service_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    exec_start = " ".join(shlex.quote(item) for item in command)
    path.write_text(
        "\n".join(
            (
                "[Unit]",
                "Description=Next Level Telegram autopublisher",
                "After=network-online.target",
                "Wants=network-online.target",
                "",
                "[Service]",
                _systemd_environment("NEXTLEVEL_ENV_FILE", str(env_file)),
                f"ExecStart={exec_start}",
                "Restart=on-failure",
                "RestartSec=10",
                "",
                "[Install]",
                "WantedBy=default.target",
                "",
            )
        ),
        encoding="utf-8",
    )
    daemon_reload = subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    enable = subprocess.run(
        ["systemctl", "--user", "enable", "--now", "nextlevel.service"],
        check=False,
    )
    return daemon_reload.returncode == 0 and enable.returncode == 0


def remove_autostart() -> bool:
    if os.name == "nt":
        result = subprocess.run(
            ["schtasks", "/Delete", "/TN", APP_NAME, "/F"], check=False
        )
        return result.returncode == 0
    if sys.platform == "darwin":
        path = Path.home() / "Library" / "LaunchAgents" / "io.github.nextlevel.bot.plist"
        subprocess.run(["launchctl", "unload", "-w", str(path)], check=False)
        if path.exists():
            path.unlink()
        return True
    subprocess.run(
        ["systemctl", "--user", "disable", "--now", "nextlevel.service"],
        check=False,
    )
    path = _linux_service_path()
    if path.exists():
        path.unlink()
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    return True


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="nextlevel", description="Telegram gaming and anime news autopublisher"
    )
    parser.add_argument(
        "command",
        nargs="?",
        default="run",
        choices=(
            "setup",
            "run",
            "once",
            "preview",
            "check",
            "config-path",
            "autostart-enable",
            "autostart-disable",
        ),
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.command == "setup":
        return setup()
    if args.command == "config-path":
        print(bot.default_env_file())
        return 0
    if args.command == "autostart-enable":
        return 0 if install_autostart() else 1
    if args.command == "autostart-disable":
        return 0 if remove_autostart() else 1
    mapping = {
        "run": [],
        "once": ["--once"],
        "preview": ["--dry-run"],
        "check": ["--check"],
    }
    return bot.main(mapping[args.command])


if __name__ == "__main__":
    raise SystemExit(main())
